### PR TITLE
Add Keyboard API

### LINKED ISSUE #99: How can I use sendkeys?
how can I send sendkeys into browser headless?

### PR DESCRIPTION
**Pull request by enricodias**
Adds Keyboard API with tests and documentation.

Resolves #99

### CODE REVIEW

**Comment by sincorecom** [comment]
How come this hasn't been merged into the main branch? I tested it on my end and it worked perfectly.

**Comment by GrahamCampbell** [comment]
It needs a careful review, ideally by more than one person.

**Comment by GrahamCampbell** [comment]
I have not got around to reviewing this yet, myself.

**Comment by sincorecom** [comment]
> I have not got around to reviewing this yet, myself.

I copied down the changes and have been using it in my own projects. Woks perfect for me :)

**Comment by GrahamCampbell** [comment]
Thanks for the excellent work. 🍻

**Pull request merged**
