### PR TITLE
[1.12] Add the ability to screenshot individual elements on the page

### PR DESCRIPTION
**Pull request by osbre**
Note that currently, the position X and Y properties are not being recorded correctly because the type is `int`, while the original X and Y type can be float. This PR fixes it as well.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is probably still broken because width and height have to be ints, so you are just getting the top left corner position correct, but not the bottom right?

**Comment by GrahamCampbell** [comment]
Are you able to test the change I pushed up work, please, and confirm that all 4 things are floats (and not just degenerate floats with a .0), passed through to chrome?

**Comment by osbre** [comment]
Tested, here is the data sample:

```php
dd($element->getClip());
```
```
Clip (instance) {
  #x: 8.0
  #y: 79.875
  #height: 21.0
  #width: 784.0
  #scale: 1.0
}
```

Seems correct. (no fake floats)

Thanks!

**Comment by enricodias** [comment]
That's a really simple but extremely useful feature 👍

**Review by enricodias — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
The width and height look wrong. Surely those should also be fractional?

**Comment by osbre** [comment]
@GrahamCampbell If you meant that the window `width` and `height` need to be `int` instead of `float` - that's correct according to the code I've tried running. Getting this error if passed float:

```
Invalid parameters - Failed to deserialize params.height - BINDINGS: int32 value expected at position 23
```

**Comment by osbre** [comment]
@GrahamCampbell Sorry for asking, but what do you mean by saying "fractional" in this context?

**Comment by GrahamCampbell** [comment]
Fractional as in floats that are not ending in `.0`

**Comment by GrahamCampbell** [comment]
Awaiting reply from @osbre.

**Comment by osbre** [comment]
@GrahamCampbell Did a test which confirmed that the width/height will be fractional if the element's width/height is explicitly set to a fractional number or is a percentage.

```php
$page->navigate($this->sitePath('fractional.html'))->waitForNavigation();

$element = $page->dom()->querySelector('#fractional');
self::assertEquals(90.5, $element->getClip()->getWidth());
```

```html
<html>
<body>
<p id="fractional" style="color: red; width: 90.5;">
    This element has a fractional width.
</p>
</body>
</html>
```

Should I make it a test and include it in this PR?

**Pull request merged**
