### PR TITLE
Fix mouse scroll maximum distance

### LINKED ISSUE #251: mouse bug
in mouse.php,line 182-183,width and height is wrong,The correct code is：
        $distanceX = $this->getMaximumDistance($distanceX, $visibleArea['pageX'], $scollableArea['width']);
        $distanceY = $this->getMaximumDistance($distanceY, $visibleArea['pageY'], $scollableArea['height']);

### PR DESCRIPTION
**Pull request by enricodias**
Fixes #251

### CODE REVIEW

**Comment by enricodias** [comment]
@GrahamCampbell should we send this one to the `0.11` branch? Are we still supporting v0.11?

**Comment by GrahamCampbell** [comment]
Yeh, sure. Let's fix this on 0.11.x too. :)

**Comment by enricodias** [comment]
Done.

**Comment by GrahamCampbell** [comment]
🎉

**Pull request merged**
