### PR TITLE
Suppress the depreciation error in PHP 8.1

### PR DESCRIPTION
**Pull request by luigel**
To suppress the error for the following files I added ReturnTypeWillChange attributes. The same for the Symfony symfony/symfony#41495

This PR will have a support for PHP8.1

### CODE REVIEW

**Comment by enricodias** [comment]
@GrahamCampbell should we add new workflows to run the tests with php 8.1 already?

**Comment by GrahamCampbell** [comment]
There's little point at the moment because https://github.com/chrome-php/wrench doesn't work on PHP 8.1 (the unit tests fail). If someone can get to the bottom of that first, it'd be much appreciated. Until then, I'm not keen on merging PHP 8.1 compatibility fixes here yet. It won't work properly until wrench is fixed.

**Comment by enricodias** [comment]
I'll try to take a look at it in the next days.

**Comment by GrahamCampbell** [comment]
FYI I did some investigation a few weeks back, if it helps: https://github.com/chrome-php/wrench/commits/php81-support.

**Comment by GrahamCampbell** [comment]
Gonna merge this anyway, even though we don't support PHP 8.1 yet.

**Pull request merged**
