### PR TITLE
[1.4] Prevent `Node::querySelector` from returning nodeId 0

### PR DESCRIPTION
**Pull request by Seriyyy95**
Fixes bug with zero node id.

### CODE REVIEW

**Comment by enricodias** [comment]
Why can't we have a node id `0`?

**Comment by Seriyyy95** [comment]
querySelector returns nodeId 0 when nothing found.

**Comment by enricodias** [comment]
I just tested and it really returns 0. Can you create a new test for this case? Pretty much the same as `testSearchByCssSelector`, but searching for a non-existent element and ensuring that the result is null.

https://github.com/chrome-php/chrome/blob/e9f10d0f7af33b4a58132891095c7cc525af3f11/tests/DomTest.php#L39

**Comment by Seriyyy95** [comment]
Done.

**Review by enricodias — APPROVED** [review]

**Pull request merged**
