### PR TITLE
[1.8] Allow passing the event name to wait for after setting a page's HTML

### PR DESCRIPTION
**Pull request by sanderdlm**
Continued from https://github.com/chrome-php/chrome/pull/455

### CODE REVIEW

**Comment by enricodias** [comment]
Thanks.

Can you add a mention to this in the documentation as well?

**Comment by enricodias** [comment]
We need to merge this to 1.8 since it's a new feature. Can you do a rebase?

**Comment by sanderdlm** [comment]
Rebased but the 1.7 commits are still there. Should I make a new branch starting from 1.8? Should the fix from [ab1add3](https://github.com/chrome-php/chrome/pull/456/commits/ab1add3a1519a9364a1710d17a8647263e985044) be merged into 1.8 as well?

**Comment by enricodias** [comment]
That's because there are some commits from 1.7 that are not in 1.8 yet and your branch started from 1.7. To remove commits during a rebase like this, we can do a interactive rebase and select only the commits we want,

We'll merge 1.7 into 1.8 in another PR before releasing 1.8.

**Comment by GrahamCampbell** [comment]
v1.8.0 has now been released, including this PR.

**Pull request merged**
