### PR TITLE
[0.10] Added mouse scrolling

### LINKED ISSUE #83: Scrolling
What is the best method to scroll a page with the library? I have tried addPreScript and addScriptTag to try and inject javascript and then run it, but without success.

### PR DESCRIPTION
**Pull request by enricodias**
Adds a scroll option in the mouse input. This can be used to scroll not only pages, but elements inside pages such as iframes.

Resolves #83

### CODE REVIEW

**Comment by enricodias** [comment]
This time the tests worked here even in the older versions of php. I'll try to take a look and fix it.

**Comment by GrahamCampbell** [comment]
This seems inherently flakey, so not useful even for someone using this library. Is there a way to block, waiting for chrome to finish the render?

**Comment by enricodias** [comment]
@GrahamCampbell I didn't find a better solution to this, but it worked every time in all my machines even without the `usleep`. I implemented this feature because I needed it for a project. I also didn't find any way to block the execution until the scroll finishes, do you have any suggestion?

**Comment by GrahamCampbell** [comment]
Maybe you need to wait before scrolling?

**Comment by enricodias** [comment]
@GrahamCampbell How do you feel about just printing a warning instead of an error if this test fail? It will prevent breaking the tests on github and will still warn developers about what happened.

**Comment by enricodias** [comment]
Waiting before scrolling seems to work, I should have thought about that before. 😁

**Comment by GrahamCampbell** [comment]
Great, thanks.

**Pull request merged**
