### PR TITLE
Support for environment variables

### PR DESCRIPTION
**Pull request by momala454**
Add support for environment variables, which allow to use by example xvfb by passing the DISPLAY variable in the options

### CODE REVIEW

**Comment by momala454** [comment]
the commits are a bit messup because I initially modified an old version

**Comment by momala454** [comment]
Hello, can you comment your decision to close it ?

**Comment by GrahamCampbell** [comment]
Oh, sorry. This was closed because the 0.10 branch has been deleted, in preparation for 0.11.0.

**Comment by GrahamCampbell** [comment]
I don't seem to be able to re-open this.

**Comment by GrahamCampbell** [comment]
The reason I did not merge this straight away is because there are no tests. If you could add a test or two, and re-submit to the 0.11 branch, I'll be happy to re-review and hopefully merge.

**Comment by momala454** [comment]
to test you would need to install xvfb, and run it with a specific display number, and put DISPLAY variable. This can be tested automatically ?

**Comment by GrahamCampbell** [comment]
I've merged this into 0.11, as it. :)

**Comment by momala454** [comment]
thank you!

**Comment by GrahamCampbell** [comment]
v0.11.0 has just been released, including this PR. :)

**Pull request closed without merging**
