### PR TITLE
[1.5] Switch to flatten mode

### LINKED ISSUE #220: Use "flatten" mode
The "non flatten" mode is deprecated and we should switch to flattened :
See here : 
https://vanilla.aslushnikov.com/?Target.attachToTarget

With this mode, requests are sent directly to the target instead of using "Target.sendMessageToTarget"

### LINKED ISSUE #337: Timeout issue due to target destroyed too fast
Often, depending on the website, i will have timeout during `waitForNavigation`
```HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 40s.
 at HeadlessChromium.Exception.OperationTimedOut.createFromTimeout(OperationTimedOut.php:18)
 at HeadlessChromium.Utils.tryWithTimeout(Utils.php:64)
 at HeadlessChromium.Communication.ResponseReader.waitForResponse(ResponseReader.php:115)
 at HeadlessChromium.Communication.Session.sendMessageSync(Session.php:89)
 at myImportClass.{closure}(importClass.php:851)
 at Evenement.EventEmitter.emit(EventEmitterTrait.php:123)
 at HeadlessChromium.Communication.Connection.dispatchMessage(Connection.php:394)
 at HeadlessChromium.Communication.Connection.readLine(Connection.php:340)
 at HeadlessChromium.Communication.Connection.readData(Connection.php:323)
 at HeadlessChromium.Page.getCurrentLifecycle(Page.php:356)
 at HeadlessChromium.Page.hasLifecycleEvent(Page.php:381)
 at HeadlessChromium.PageUtils.PageNavigation.navigationComplete(PageNavigation.php:173)
 at HeadlessChromium.Utils.tryWithTimeout(Utils.php:57)
 at HeadlessChromium.PageUtils.PageNavigation.waitForNavigation(PageNavigation.php:132)
```

`waitForNavigation` calls `navigationComplete` and at the end of `navigationComplete`, there is
```php
$this->page->getSession()->getConnection()->readData();
```

There is also hasLifecycleEvent that calls readData too

I believe that if I have another portion of code that calls `readData()` in the same time and that data read elsewhere contains the data `Page.lifecycleEvent`, readData will be stuck waiting for data that will never come (because all data have been read) and throw a timeout.

I suppose that to reproduce it, you can do a lot of sendMessageSync at the same time that a target is created
```php
$browser->getConnection()->on('method:Target.targetCreated', function (array $params) use (&$browser) {
$browser->getTarget($params['targetInfo']['targetId'])->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Anything'));
});
```

### PR DESCRIPTION
**Pull request by momala454**
Switch to the usage of flatten mode, which is now the prefered mode. The non flatten mode (which this library is currently using) is deprecated and will eventually be removed in the future.
Reference : 
https://vanilla.aslushnikov.com/?Target.attachToTarget

Messages are now sent directly to the target using the sessionId, instead of using `Target.sendMessageToTarget`

Resolves https://github.com/chrome-php/chrome/issues/220
Resolves https://github.com/chrome-php/chrome/issues/337

### CODE REVIEW

**Comment by enricodias** [comment]
Does the tests work locally at your end? I think they are getting stuck on the workflows and there are no logs about this.

**Comment by momala454** [comment]
i don't know, i never ran the tests actually

**Comment by momala454** [comment]
all tests are timeouting, i dont know why

**Comment by GrahamCampbell** [comment]
This PR contains major breaking changes.

**Comment by momala454** [comment]
something is broken for the moment, let me fix it.
It was working when it was based from 1.3

**Comment by momala454** [comment]
fixed,
but one test failed, maybe the timeout should be increased ?
1) HeadlessChromium\Test\DomTest::testUploadFiles
HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 2s.

edit: the tests are ok now apparently

**Comment by momala454** [comment]
last commit should fix https://github.com/chrome-php/chrome/issues/337
Only works on flatten as the message doesn't contain the sessionId without flatten.

if anyone is able to create a simple test case, i'm open, because I was not able to create one. I needed to use a real world website to test

**Comment by momala454** [comment]
can anyone review?

**Comment by enricodias** [comment]
The tests are failing intermittently due to that old timeout issue, but other than that the changes seem to work. I'm waiting to see what Graham thinks.

**Comment by momala454** [comment]
Do you know what is the timeout issue? I don't see it on the other pr. Should I try to solve it?

**Comment by enricodias** [comment]
> Do you know what is the timeout issue? 

I don't know whats causing it, but it hasn't happened in the last PRs.

**Pull request merged**
