### PR TITLE
Fixed issues with `Keyboard::typeText` with multibyte strings

### PR DESCRIPTION
**Pull request by YandievRuslan**
Exception HeadlessChromium\Exception\CommunicationException\InvalidResponse throws when you try to type unicode string keyboard()->typeText("Юникод строка")

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for this. Could you add a test please.

**Comment by YandievRuslan** [comment]
Are you about code to reproduce the error?

```
$browserFactory = new BrowserFactory('chromium-browser');
$browser = $browserFactory->createBrowser(['windowSize' => [1920, 1080], 'headless' => false]);
$url = 'https://yandex.ru';
page->navigate($url)->waitForNavigation();
$page->dom()->querySelector('#text')->click();
sleep(1);
//here will be the error
$page->keyboard()->typeText('Со Г1алг1а ва');
sleep(5);
$page->close();
$browser->close();
```
Is this enough?

**Comment by GrahamCampbell** [comment]
No, I'm asking you to include a test in our test suite as part of this PR.

**Comment by YandievRuslan** [comment]
Bro, i'm not familiar with English and i don't understand what do you want from me. You should tell more detail.

**Comment by GrahamCampbell** [comment]
Please add code to https://github.com/chrome-php/chrome/tree/1.3/tests.

**Comment by YandievRuslan** [comment]
ok, to KeyboardApiTest.php?

**Comment by YandievRuslan** [comment]
Is it right?

**Comment by enricodias** [comment]
Shouldn't we also add this in the previous versions?

**Comment by GrahamCampbell** [comment]
Previous versions?

**Comment by enricodias** [comment]
The 1.1 and 1.2 branches.

**Comment by GrahamCampbell** [comment]
No. People can upgrade to 1.3.1. We follow semver. :)

**Review by enricodias — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Thanks. 🍻

**Pull request merged**
