### PR TITLE
[1.10] Allow to remove default chrome flags via option excludedSwitches

### PR DESCRIPTION
**Pull request by momala454**
Example, to remove the bar "Chrome is being controlled ...", you must not send the flag `--enable-automation`, so by adding this flag to the excludedSwitches, the bar is absent.

### CODE REVIEW

**Comment by enricodias** [comment]
The reason you don't just do `$args = \array_diff($args, $options['excludedSwitches']);` is because there are some options with values that wouldn't match, right? If we do something like this we'll have the same effect but without needing to put the extra `--`:

```php
if (\array_key_exists('excludedSwitches', $options) && \is_array($options['excludedSwitches'])) {
    $excludedArgs = \implode(',', $options['excludedSwitches']);
    $args = \array_filter($args, function ($arg) use ($excludedArgs) {
        return \stripos($arg, $excludedArgs) === false;
    });
}
```

But that look awful.

Can't we just remove the options that have no value using `array_diff`? The ones that have value the user can override with his own value, even an empty value. Actually, passing the value with the switch in the `excludedSwitches` will work too, since it will work as a generic filter.

There's also a docblock describing those options that would need to be updated here: https://github.com/chrome-php/chrome/blob/ab591afbfd973e1950a07c166d2f60f7e13033d7/src/BrowserFactory.php#L28-L50

The docs also need to state that this option expects an array, not just a string.

And btw, I tested here and chrome still shows the message that chrome is being controlled, even without the switch `--enable-automation`.

**Comment by momala454** [comment]
i'm not using array_diff to not have to put exactly the full parameter, if we have by example
`--user-data-dir=/home/hello`

having as excluded `--user-data-dir` without having to write the parameter value will work.
stripos could cause false positive if you exclude --user but you have a parameter --user-data-dir by example

I have tested on windows and I also modified another preference (CommandLineFlagSecurityWarningsEnabled to false) via a policy (https://sites.google.com/a/chromium.org/dev/administrators/windows-quick-start). The policy itself without the enable-automation removing didn't worked, maybe it's the combination of the two changes that made it work,


some parameters like proxy-server, user-agent, --remote-debuguing-port are varying, so having to put exactly the value that was provided could be a bit difficult.
Maybe remove the excludedSwitches before adding the custom flags so we can remove the default one and put our custom ones

**Comment by enricodias** [comment]
> stripos could cause false positive if you exclude --user but you have a parameter --user-data-dir by example

Good catch, I missed that case.

The `user-data-dir` is the only one we can't filter out using `array_diff` because we don't know its default value, right? But if we just filter it like you are doing, a temp folder will still be created and removed after each execution: https://github.com/chrome-php/chrome/blob/ab591afbfd973e1950a07c166d2f60f7e13033d7/src/Browser/BrowserProcess.php#L107-L109
If the only reason for filtering the user dir is to let chrome use its default profile, maybe we should just have a method for that and ignore all things related to the user dir entirely.

All the other options with values can be overwritten and the ones without value can be filtered out with a simple diff.

**Comment by momala454** [comment]
User data dit was just an example. User agent is also configured elsewhere, the values of some default parameters could also be modified between lib versions, so one could want to be able to remove parameters regardless of the value.

**Comment by enricodias** [comment]
But we can, by overwriting them with our own values. The lib uses the default values only when the option isn't defined, except for those first ones like the `enable-automation` in your example, that could be filtered with a simple diff. The first 2 options on that list have values (remote-debugging-port and remote-allow-origins), but we wouldn't be able to control chrome without them.

The `user-data-dir` is special because it's used elsewhere. If we're gonna let the user not use any dir, we should not create and remove a temp folder in those cases. So this would require more than a simple filter.

We can't let the user filter values that will prevent the lib from controlling chrome. It will timeout and I think that chrome process could remain alive after the php process dies.

The recent changes in the `getHtml` are not related to this feature.

**Review by enricodias — APPROVED** [review]

**Comment by momala454** [comment]
@GrahamCampbell can this be merged please ? thanks

**Comment by GrahamCampbell** [comment]
Thanks.

**Pull request merged**
