### PR TITLE
Use `--disable-notifications` flag to disable notifications

### PR DESCRIPTION
**Pull request by buismaarten**

### CODE REVIEW

**Comment by buismaarten** [comment]
Some tests failed unexpectedly, can you run again?

**Comment by enricodias** [comment]
Adding that way will break backwards compatibility as there may be people parsing notifications with this lib. Making it customizable with the `$options` argument is safer.

**Comment by buismaarten** [comment]
Yeah, I didn't think of that.. I'll make the changes to soon.

**Comment by enricodias** [comment]
And since it will be a new feature, it should be in v1.9 too.

**Pull request closed without merging**
